name: Nombrecin ${{inputs.custom}}

on:
  workflow_dispatch:
    inputs:
      custom:
        description: 'Custom parameter, can be used in script as ${CUSTOM}'
        required: false
        default: 'value'
        type: string


jobs:
  get-branch-name:
    runs-on: ubuntu-latest

    steps:
      - name: Imprimir nombre de la rama
        run: |
          echo "Nombre de la rama: ${GITHUB_REF#refs/heads/}"
