name: Local test

on:
  workflow_dispatch:
    inputs:
      script:
        description: "Jmeter Script"
        required: true
        default: "Client.jmx"
        type: string
      environment:
        description: "Execution environment"
        required: true
        default: "per"
        type: choice
        options:
          - stg-test
          - per
      crConfig:
        description: "CR configuration"
        required: true
        default: "production-copy"
        type: choice
        options:
          - none
          - single-container
          - scalability
          - production-copy
      target:
        description: "Concurrency target or TSP property"
        required: true
        default: "1000"
        type: string
      startupTime:
        description: "Start up (seconds)"
        required: false
        default: 1200
        type: number
      duration:
        description: "Duration (seconds)"
        required: false
        default: 1200
        type: number
      shutDownTime:
        description: "Shut down (seconds)"
        required: false
        default: 300
        type: number
      slack:
        description: "Slack channel ID"
        required: false
        default: "C02RE9ZBZL3"
        type: string
      useStaticAddress:
        description: "Use static IP address?"
        required: false
        default: false
        type: boolean
env:
  CONFIG_FILE: config.yaml
  ENV_FILE: ${{ inputs.environment }}.yaml

jobs:
  test-local-job:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: 'actions/checkout@v4'

      - name: wait for instances
        run: |
          #!/bin/bash
          chmod +x ./script.sh
          ./script.sh "andele"



