name: Obtener nombre de la rama

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Nombre de la rama'
        required: false

jobs:
  get-branch-name:
    runs-on: ubuntu-latest

    steps:
      - name: Imprimir nombre de la rama
        run: |
          echo "Nombre de la rama: ${GITHUB_REF#refs/heads/}"
