name: For test-learn purpose Only
on:

  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment where test will be executed'
        required: true
        default: 'per'
        type: choice
        options:
          - stg
          - per
env:
  SLACK_NOTIFICATIONS: false

jobs:
  test_steps:
    name: Testing steps
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Test
        run: |
          echo "Nombre de la rama actual: ${{ env.GITHUB_REF_NAME }}"